//! Integration tests against a realistic simulated alignment.
//!
//! The fixture `testdata/clean/sim_protein_20x300.fasta` is 20 sequences of
//! 300 columns of simulated protein: ragged 5'/3' ends, two well-conserved
//! cores, a hypervariable indel-rich region between them and a scattering of
//! isolated gaps inside the cores. It is generated by the deterministic
//! xorshift PRNG in [`simulate`] below (no `rand` dependency), and
//! [`fixture_matches_the_generator`] checks the committed file still matches,
//! so the fixture is reproducible from this file alone.

use std::ops::Range;
use std::path::PathBuf;

use tolviewer_clean::{
    gblocks, remove_gappy_columns, remove_gappy_sequences, trim_ends, ColumnFlag, GapPolicy,
    GblocksParams,
};
use tolviewer_core::{Alignment, Alphabet, Sequence};

// ---------------------------------------------------------------------------
// Fixture
// ---------------------------------------------------------------------------

const AA: &[u8; 20] = b"ACDEFGHIKLMNPQRSTVWY";
const ROWS: usize = 20;
const WIDTH: usize = 300;

/// xorshift64: three lines, deterministic, and quite good enough to sprinkle
/// substitutions over a consensus.
struct Xorshift(u64);

impl Xorshift {
    fn new(seed: u64) -> Self {
        Xorshift(seed)
    }
    fn next_u32(&mut self) -> u32 {
        self.0 ^= self.0 << 13;
        self.0 ^= self.0 >> 7;
        self.0 ^= self.0 << 17;
        (self.0 >> 32) as u32
    }
    fn below(&mut self, n: u32) -> u32 {
        self.next_u32() % n
    }
}

#[derive(Clone, Copy, PartialEq)]
enum Region {
    /// Ragged terminus: unalignable, and rows start and end at random offsets.
    Ragged,
    /// Conserved core: 90% consensus, 10% substitutions, rare isolated gaps.
    Core,
    /// Hypervariable: random residues and a quarter of the cells deleted.
    Hyper,
}

fn region(col: usize) -> Region {
    match col {
        0..=19 => Region::Ragged,
        20..=119 => Region::Core,
        120..=159 => Region::Hyper,
        160..=279 => Region::Core,
        _ => Region::Ragged,
    }
}

/// Regenerate the fixture in memory.
fn simulate() -> Vec<(String, Vec<u8>)> {
    let mut rng = Xorshift::new(0x5EED_1234_ABCD_EF01);
    let consensus: Vec<u8> = (0..WIDTH).map(|_| AA[rng.below(20) as usize]).collect();
    let mut rows = Vec::with_capacity(ROWS);
    for r in 0..ROWS {
        let first = rng.below(18) as usize;
        let last = WIDTH - 1 - rng.below(18) as usize;
        let mut residues = Vec::with_capacity(WIDTH);
        for (col, &cons) in consensus.iter().enumerate() {
            if col < first || col > last {
                residues.push(b'-');
                continue;
            }
            let roll = rng.below(1000);
            residues.push(match region(col) {
                Region::Core => match roll {
                    0..=1 => b'-',
                    2..=99 => AA[rng.below(20) as usize],
                    _ => cons,
                },
                Region::Hyper => match roll {
                    0..=249 => b'-',
                    _ => AA[rng.below(20) as usize],
                },
                Region::Ragged => match roll {
                    0..=99 => b'-',
                    _ => AA[rng.below(20) as usize],
                },
            });
        }
        rows.push((format!("taxon_{r:02}"), residues));
    }
    rows
}

fn fixture_path() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("../../testdata/clean/sim_protein_20x300.fasta")
}

/// A minimal FASTA reader. `tolviewer-clean` does not depend on
/// `tolviewer-io` (they are siblings in the dependency graph), and six lines
/// of parser is cheaper than inverting that.
fn read_fasta(text: &str) -> Alignment {
    let mut sequences: Vec<Sequence> = Vec::new();
    for line in text.lines() {
        let line = line.trim();
        if let Some(header) = line.strip_prefix('>') {
            sequences.push(Sequence::new(header.to_string(), Vec::new()));
        } else if !line.is_empty() {
            let last = sequences.last_mut().expect("FASTA data before any header");
            last.residues.extend_from_slice(line.as_bytes());
        }
    }
    let mut aln = Alignment::new("sim_protein_20x300", sequences);
    aln.set_alphabet(Alphabet::Protein);
    aln
}

fn fixture() -> Alignment {
    let text = std::fs::read_to_string(fixture_path())
        .unwrap_or_else(|e| panic!("cannot read {}: {e}", fixture_path().display()));
    read_fasta(&text)
}

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

#[test]
fn fixture_matches_the_generator() {
    let aln = fixture();
    let expected = simulate();
    assert_eq!(aln.len(), ROWS);
    assert_eq!(aln.width(), WIDTH);
    assert!(aln.is_aligned());
    for (seq, (id, residues)) in aln.sequences.iter().zip(&expected) {
        assert_eq!(&seq.id, id);
        assert_eq!(&seq.residues, residues, "row {id} differs from the generator");
    }
}

#[test]
fn defaults_keep_a_sensible_fraction() {
    let aln = fixture();
    let params = GblocksParams::defaults(aln.len());
    assert_eq!((params.min_seqs_conserved, params.min_seqs_flank), (11, 17));
    let r = gblocks(&aln, &params).unwrap();

    let f = r.kept_fraction();
    assert!(
        (0.30..0.85).contains(&f),
        "default Gblocks kept {f} of the columns ({} of {})",
        r.kept,
        r.total
    );

    // The two conserved cores must be well represented and the hypervariable
    // region and ragged ends must be gone.
    let kept_in = |range: Range<usize>| r.mask[range.clone()].iter().filter(|&&k| k).count();
    assert_eq!(kept_in(0..20), 0, "the ragged 5' end must be rejected");
    assert_eq!(kept_in(280..300), 0, "the ragged 3' end must be rejected");
    assert_eq!(kept_in(120..160), 0, "the hypervariable region must be rejected");
    assert!(kept_in(20..120) > 50, "too little of the first core survived");
    assert!(kept_in(160..280) > 60, "too little of the second core survived");

    // Every block is at least b4 long and its edges are at least conserved.
    // They need not be *highly* conserved: gap cleaning runs after the flank
    // step and stops "until a conserved position is reached", so a block that
    // gap cleaning cut in two gets a merely-conserved new edge. That is the
    // published order of operations (flanks, then gap cleaning, then b4) and
    // this test pins the consequence.
    for b in &r.blocks {
        assert!(b.len() >= params.min_block_length, "short block {b:?}");
        assert!(r.flags[b.start].is_conserved(), "block {b:?} starts on {:?}", r.flags[b.start]);
        assert!(r.flags[b.end - 1].is_conserved(), "block {b:?} ends on {:?}", r.flags[b.end - 1]);
    }
    // With b5 = None no kept column may contain a gap.
    assert!(!r.mask.iter().zip(&r.flags).any(|(&k, &f)| k && f == ColumnFlag::GapRich));

    // Without gap cleaning to disturb them, block edges *are* flank columns.
    let mut no_gap_cleaning = params.clone();
    no_gap_cleaning.gaps = GapPolicy::All;
    let all = gblocks(&aln, &no_gap_cleaning).unwrap();
    for b in &all.blocks {
        assert!(all.flags[b.start].is_flank(), "block {b:?} start under b5 = all");
        assert!(all.flags[b.end - 1].is_flank(), "block {b:?} end under b5 = all");
    }
}

#[test]
fn relaxed_keeps_strictly_more_than_the_defaults() {
    let aln = fixture();
    let strict = gblocks(&aln, &GblocksParams::defaults(aln.len())).unwrap();
    let relaxed = gblocks(&aln, &GblocksParams::relaxed(aln.len())).unwrap();

    assert!(
        relaxed.kept > strict.kept,
        "relaxed kept {} but the defaults kept {}",
        relaxed.kept,
        strict.kept
    );
    assert!(relaxed.kept_fraction() < 1.0, "even relaxed must drop the ragged ends");

    // Relaxing every parameter can only add columns, so the strict selection
    // has to be a subset of the relaxed one.
    for (col, (&strict_keep, &relaxed_keep)) in strict.mask.iter().zip(&relaxed.mask).enumerate() {
        assert!(
            !strict_keep || relaxed_keep,
            "column {col} is kept by the defaults but dropped when relaxed"
        );
    }
}

#[test]
fn gap_policy_is_monotone_on_real_data() {
    let aln = fixture();
    let mut previous = 0usize;
    for &policy in GapPolicy::all() {
        let mut p = GblocksParams::defaults(aln.len());
        p.gaps = policy;
        let kept = gblocks(&aln, &p).unwrap().kept;
        assert!(
            kept >= previous,
            "{} kept {kept}, fewer than the previous policy's {previous}",
            policy.name()
        );
        previous = kept;
    }
    assert!(previous > 0);
}

#[test]
fn apply_preserves_rows_and_names_and_agrees_with_the_mask() {
    let aln = fixture();
    let r = gblocks(&aln, &GblocksParams::defaults(aln.len())).unwrap();
    let cleaned = r.apply(&aln).unwrap();

    assert_eq!(cleaned.width(), r.kept);
    assert_eq!(cleaned.len(), aln.len());
    assert!(cleaned.is_aligned());
    for (before, after) in aln.sequences.iter().zip(&cleaned.sequences) {
        assert_eq!(before.id, after.id);
        let expected: Vec<u8> =
            before.residues.iter().zip(&r.mask).filter(|(_, &k)| k).map(|(&c, _)| c).collect();
        assert_eq!(after.residues, expected);
    }
    assert_eq!(r.mask_line().len(), WIDTH);
    assert_eq!(r.mask_line().matches('#').count(), r.kept);
}

#[test]
fn deterministic_and_idempotent_on_real_data() {
    let aln = fixture();
    let params = GblocksParams::defaults(aln.len());
    let first = gblocks(&aln, &params).unwrap();
    assert_eq!(first, gblocks(&aln, &params).unwrap());

    // Cleaning an already-cleaned alignment is a no-op. b1/b2 depend only on
    // the row count, which `apply` does not change, so the same parameters
    // apply unchanged.
    let cleaned = first.apply(&aln).unwrap();
    let second = gblocks(&cleaned, &params).unwrap();
    assert_eq!(
        second.kept,
        second.total,
        "re-running dropped {} columns",
        second.total - second.kept
    );
    assert_eq!(second.blocks, vec![0..cleaned.width()]);
    assert_eq!(second.apply(&cleaned).unwrap(), cleaned);
}

#[test]
fn simple_filters_agree_with_the_shape_of_the_fixture() {
    let aln = fixture();

    // The ragged ends are the only columns that are more than half gaps
    // outside the hypervariable region.
    let columns = remove_gappy_columns(&aln, 0.2);
    assert_eq!(columns.len(), WIDTH);
    assert!(!columns[0], "column 0 is mostly gaps");
    assert!(columns[200], "the middle of a core should survive");
    assert!(columns.iter().filter(|&&k| !k).count() > 20);

    // No row is anywhere near half gaps, so nothing is dropped at 0.5.
    let rows = remove_gappy_sequences(&aln, 0.5);
    assert_eq!(rows.len(), ROWS);
    assert!(rows.iter().all(|&k| k));
    // ... but demanding a gap-free row drops every one of them.
    assert!(remove_gappy_sequences(&aln, 0.0).iter().all(|&k| !k));

    // Full occupancy is only reached inside the sequence, so the ends trim.
    let range = trim_ends(&aln, 1.0);
    assert!(range.start > 0 && range.end < WIDTH, "trim_ends returned {range:?}");
    assert!(range.len() > WIDTH / 2);
    assert_eq!(trim_ends(&aln, 0.0), 0..WIDTH);
}
